version: "3.9"

services:
  advella-backend:
    container_name: "advella-backend"
    build: advella-backend
    restart: unless-stopped
    environment:
      - ${MSSQL_PASSWORD}
    ports:
      - 3000:8080
    volumes:
      - advella-backend:/app
    networks:
      - advella_prod
      
  advella-frontend-webapp:
    container_name: "advella-frontend-webapp"
    build: advella-frontend-webapp
    restart: unless-stopped
    ports:
      - 3001:80
    networks:
      - advella_prod
      
  advella-frontend-webapp-admin:
    container_name: "advella-frontend-webapp-admin"
    build: advella-frontend-webapp-admin
    restart: unless-stopped
    ports:
      - 3002:80
    networks:
      - advella_prod
      
volumes:
  advella-backend:

networks:
  advella_prod:
    name: advella
    driver: bridge
    internal: false
    
