version: "3.9"

services:
  db:
    container_name: "mssql"
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - SA_PASSWORD=${MSSQL_PASSWORD}
      - ACCEPT_EULA="Y"
    ports:
      - 1443:1443
    networks:
      - advella_init
  nginx-proxy-manager:
    container_name: "nginx-proxy-manager"
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - /opt/containers/nginx-proxy-manager:/data
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - advella_init

networks:
  advella_init:
    name: advella
    driver: bridge
    internal: false
