version: "3.9"

services:
  advella-backend:
    container_name: "advella-backend"
    build: advella-backend
    environment:
      - ${MSSQL_PASSWORD}
    volumes:
      - /opt/containers/advella/backend:/server
    ports:
      - 3000:8080
    networks:
      - advella_prod
      
  advella-frontend-webapp:
    container_name: "advella-frontend-webapp"
    build: advella-frontend-webapp
    volumes:
      - /opt/containers/advella/frontend-webapp:/app
    ports:
      - 3001:80
    networks:
      - advella_prod
      
  advella-frontend-webapp-admin:
    container_name: "advella-frontend-webapp-admin"
    build: advella-frontend-webapp-admin
    volumes:
      - /opt/containers/advella/frontend-webapp-admin:/app
    ports:
      - 3002:80
    networks:
      - advella_prod

networks:
  advella_prod:
    name: advella
    driver: bridge
    internal: false
    
